# Generated by Django 5.0.2 on 2024-02-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FileSys", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
