# Generated by Django 5.0.2 on 2024-02-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FileSys", "0002_alter_file_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(upload_to="uploads/"),
        ),
    ]
