# Generated by Django 5.0.2 on 2024-02-17 08:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("FileSys", "0003_alter_file_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="folder",
        ),
    ]
